### ISSUE TITLE
UI should generate a button for setting which is declared as JDBC_TABLE

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1149] opened 2019-05-14 02:40 UTC
#1107 has added JDBC_TABLE type to setting. It is a specific string saying it's input is associated to a table of remote database. As a friendly UI, it would be better to generate a button (or a page) to user to select the table of remote database directly. [Query APIs](https://github.com/oharastream/ohara/blob/master/docs/rest_interface.md#query) can help UI to fetch all tables from remote database.

**Comment by chia7712** [comment] 2019-05-14 02:40
ping @eechih @wu87988622 @konekoya

**Comment by konekoya** [comment] 2019-05-14 03:48
Have talked with @eechih about this last Friday. We're going to implement this while we're upgrading connectors in #1049 

/cc @wu87988622 since he'll be in charge of refactoring this connector

**Comment by chia7712** [comment] 2019-05-14 04:00
>Have talked with @eechih about this last Friday. We're going to implement this while we're upgrading connectors in #1049

Please close this issue if it is duplicate to #1049

**Comment by konekoya** [comment] 2019-05-14 05:35
> Please close this issue if it is duplicate to #1049

No problem. And we've opened another sub-issue #1100 to tackle this

**Comment by konekoya** [comment] 2019-05-14 05:36
Dupe of #1100

**Closed by konekoya** 2019-05-14 05:35 UTC
Labels: v0.5.0
