### ISSUE TITLE
Fail to upload stream jar if we have deployed plugin on worker

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4715] opened 2020-05-05 16:12 UTC
how to reproduce this bug ?

1. upload a plugin to worker
1. upload a stream jar in pipeline page (not working)

**Comment by chia7712** [comment] 2020-05-05 16:13
FYI @oharastream/frontend

**Comment by saivirtue** [comment] 2020-05-06 01:34
Since we disable upload plugins when creating a workspace (#4522), this issue could not reproduce in the current version. I will test the same scenario in 0.9 later

**Comment by saivirtue** [comment] 2020-05-06 02:10
Unfortunately, this is a bug :(
Do we need to fix this bug in `0.9.1`?

**Comment by chia7712** [comment] 2020-05-06 02:23
It seems to me we should move on to 0.10.0 ASAP so we don’t need to backport to 0.9.1

**Comment by vitojeng** [comment] 2020-05-06 03:31
> It seems to me we should move on to 0.10.0 ASAP so we don’t need to backport to 0.9.1

Totally agree. We should focus fixing on v0.10.0 and then move to v0.10.0 ASAP.

**Comment by saivirtue** [comment] 2020-05-13 06:00
Since this issue will not backport to 0.9 and should be fixed after 0.10, I will close this issue later.

**Closed** 2020-05-14 08:23 UTC
Labels: bug, needs investigation, v0.9.0
